# Instalando bibliotecas

In [10]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib64/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib64/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib64/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib64/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.venv/lib64/python3.14/site-packages (from seaborn) (2.5.4)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib64/python3.14/site-packages (from seaborn) (3.0.6)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.11.2-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.4.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.67.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (137 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.5.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib64/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Collecting pillow>=9 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-13.0.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib64/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib64/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.11.2-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 28.0 MB/s  0:00:00eta 0:00:01
Downloading contourpy-1.4.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (384 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.67.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 41.4 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.0 MB/s  0:00:01m eta 0:00:01
Downloading pillow-13.0.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 41.1 MB/s  0:00:00
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [seaborn]m7/8 [seaborn]ib]
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3 seaborn-0.13.2

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [12]:
pip install plotly.express

Collecting plotly.express
  Downloading plotly_express-0.4.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=0.20.0 in ./.venv/lib64/python3.14/site-packages (from plotly.express) (3.0.6)
Collecting plotly>=4.1.0 (from plotly.express)
  Downloading plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting statsmodels>=0.9.0 (from plotly.express)
  Downloading statsmodels-0.15.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting scipy>=0.18 (from plotly.express)
  Downloading scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting patsy>=0.5 (from plotly.express)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: numpy>=1.11 in ./.venv/lib64/python3.14/site-packages (from plotly.express) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib64/python3.14/site-packages (from pandas>=0.20.0->plotly.express) (2.9.0.post0)
Requirement already satisfied: packaging in ./.venv/lib64/python3.14/site-packages (from patsy>=0.5->plotly.express) (26.3)
Collecting narwhals>=1.15.1 (from plotly>=4.1.0->plotly.express)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib64/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly.express) (1.17.0)
Collecting formulaic>=1.1.0 (from statsmodels>=0.9.0->plotly.express)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in ./.venv/lib64/python3.14/site-packages (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express) (4.16.0)
Collecting wrapt>=1.17.0rc1 (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express)
  Downloading wrapt-2.5.2rc1-cp314-cp314-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.6 kB)
Downloading plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
Downloading plotly-7.1.0-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 24.0 MB/s  0:00:00 eta 0:00:01
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 31.4 MB/s  0:00:01 eta 0:00:01
Downloading statsmodels-0.15.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 40.1 MB/s  0:00:00eta 0:00:01
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading wrapt-2.5.2rc1-cp314-cp314-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (251 kB)
Installing collected packages: wrapt, scipy, patsy, narwhals, interface-meta, plotly, formulaic, statsmodels, plotly.express
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [plotly.express]m [statsmodels]
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 narwhals-2.27.1 patsy-1.0.3 plotly-7.1.0 plotly.express-0.4.1 scipy-1.18.1 statsmodels-0.15.0 wrapt-2.5.2rc1

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Importando bibliotecas

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## Exploração dos dados

In [16]:
base_irrigation = pd.read_csv('dados_manaus_horarios.csv')

In [17]:
base_irrigation

,timestamp,air_temperature_c,relative_humidity_pct,soil_moisture_pct,solar_radiation_wm2
0,2023-01-01T00:00,24.7,93,40.3,0.0
1,2023-01-01T01:00,24.0,96,40.2,0.0
2,2023-01-01T02:00,24.3,96,40.1,0.0
3,2023-01-01T03:00,24.4,96,40.0,0.0
4,2023-01-01T04:00,23.9,97,39.9,0.0
...,...,...,...,...,...
26299,2025-12-31T19:00,26.4,88,38.7,1.0
26300,2025-12-31T20:00,26.7,85,36.0,0.0
26301,2025-12-31T21:00,26.6,86,36.0,0.0
26302,2025-12-31T22:00,26.5,86,36.0,0.0
26303,2025-12-31T23:00,26.2,89,35.9,0.0

In [18]:
base_irrigation.head(10)

,timestamp,air_temperature_c,relative_humidity_pct,soil_moisture_pct,solar_radiation_wm2
0,2023-01-01T00:00,24.7,93,40.3,0.0
1,2023-01-01T01:00,24.0,96,40.2,0.0
2,2023-01-01T02:00,24.3,96,40.1,0.0
3,2023-01-01T03:00,24.4,96,40.0,0.0
4,2023-01-01T04:00,23.9,97,39.9,0.0
5,2023-01-01T05:00,24.0,96,39.9,0.0
6,2023-01-01T06:00,24.0,96,39.8,0.0
7,2023-01-01T07:00,25.4,91,39.7,34.0
8,2023-01-01T08:00,25.9,87,40.0,113.0
9,2023-01-01T09:00,26.8,82,39.8,474.0

In [19]:
base_irrigation.tail(10)

,timestamp,air_temperature_c,relative_humidity_pct,soil_moisture_pct,solar_radiation_wm2
26294,2025-12-31T14:00,28.4,76,38.6,486.0
26295,2025-12-31T15:00,27.2,80,39.9,435.0
26296,2025-12-31T16:00,26.9,79,39.6,414.0
26297,2025-12-31T17:00,27.1,80,39.1,259.0
26298,2025-12-31T18:00,26.8,84,38.9,81.0
26299,2025-12-31T19:00,26.4,88,38.7,1.0
26300,2025-12-31T20:00,26.7,85,36.0,0.0
26301,2025-12-31T21:00,26.6,86,36.0,0.0
26302,2025-12-31T22:00,26.5,86,36.0,0.0
26303,2025-12-31T23:00,26.2,89,35.9,0.0

In [20]:
base_irrigation.describe()

,air_temperature_c,relative_humidity_pct,soil_moisture_pct,solar_radiation_wm2
count,26304.000000,26304.000000,26304.000000,26304.000000
mean,27.850023,79.155870,28.008219,224.196472
std,2.604971,13.911784,11.102316,295.780909
min,21.500000,29.000000,0.000000,0.000000
25%,25.900000,71.000000,17.100000,0.000000
50%,27.300000,83.000000,31.200000,6.500000
75%,29.400000,90.000000,37.900000,456.000000
max,37.700000,100.000000,43.300000,1028.000000